apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: worker
spec:
  template:
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
            - image: us-east1-docker.pkg.dev/personal-gcp-477623/github-scraper/worker:1.2.7
              resources:
                limits:
                  cpu: '1'
                  memory: '512Mi'
              env:
                - name: NODE_ENV
                  value: production
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: db-url
                      key: latest
                - name: REDIS_HOST
                  valueFrom:
                    secretKeyRef:
                      name: redis-host
                      key: latest
                - name: REDIS_PORT
                  valueFrom:
                    secretKeyRef:
                      name: redis-port
                      key: latest
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis-password
                      key: latest
                - name: REDIS_TLS
                  value: 'true'
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-token
                      key: latest
                - name: USE_R2_STORAGE
                  value: 'true'
                - name: R2_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: r2-account-id
                      key: latest
                - name: R2_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: r2-access-key
                      key: latest
                - name: R2_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: r2-secret-key
                      key: latest
                - name: R2_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: r2-bucket
                      key: latest
