apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    autoscaling.knative.dev/minScale: '0'
    autoscaling.knative.dev/maxScale: '3'
    run.googleapis.com/cpu-throttling: 'true'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '80'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      serviceAccountName: default
      containers:
        - image: gcr.io/personal-gcp-477623/api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '1'
              memory: '512Mi'
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '8080'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: latest
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-host
                  key: latest
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-port
                  key: latest
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: latest
            - name: REDIS_TLS
              value: 'true'
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: latest
            - name: USE_R2_STORAGE
              value: 'true'
            - name: R2_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: r2-account-id
                  key: latest
            - name: R2_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: r2-access-key
                  key: latest
            - name: R2_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: r2-secret-key
                  key: latest
            - name: R2_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: r2-bucket
                  key: latest
            - name: FRONTEND_URL
              value: 'https://YOUR_FIREBASE_PROJECT.web.app'
            - name: BACKEND_URL
              value: 'https://api-YOUR_HASH.us-east1.run.app'
  traffic:
    - percent: 100
      latestRevision: true
