#!/bin/bash
# Quick reference for viewing production logs
# This script shows various ways to access logs

PROJECT_ID="personal-gcp-477623"
REGION="us-east1"
SERVICE_NAME="api"
JOB_NAME="worker"

echo "📋 Production Logs - Quick Reference"
echo "===================================="
echo ""
echo "1️⃣  View API Logs (Recent):"
echo "   ./view-prod-logs.sh api"
echo ""
echo "2️⃣  View Worker Logs (Recent):"
echo "   ./view-prod-logs.sh worker"
echo ""
echo "3️⃣  View Both (Recent):"
echo "   ./view-prod-logs.sh both"
echo ""
echo "4️⃣  Stream API Logs (Live):"
echo "   ./view-prod-logs.sh api --tail"
echo ""
echo "5️⃣  Stream Worker Logs (Live):"
echo "   ./view-prod-logs.sh worker --tail"
echo ""
echo "6️⃣  View Errors Only:"
echo "   ./view-prod-logs.sh errors"
echo ""
echo "7️⃣  Manual Commands:"
echo ""
echo "   API Logs (last 50):"
echo "   gcloud logging read \"resource.type=cloud_run_revision AND resource.labels.service_name=${SERVICE_NAME} AND resource.labels.location=${REGION}\" --project=${PROJECT_ID} --limit=50"
echo ""
echo "   Worker Logs (last 50):"
echo "   gcloud logging read \"resource.type=cloud_run_job AND resource.labels.job_name=${JOB_NAME} AND resource.labels.location=${REGION}\" --project=${PROJECT_ID} --limit=50"
echo ""
echo "   Stream API Logs:"
echo "   gcloud logging tail \"resource.type=cloud_run_revision AND resource.labels.service_name=${SERVICE_NAME} AND resource.labels.location=${REGION}\" --project=${PROJECT_ID}"
echo ""
echo "   Stream Worker Logs:"
echo "   gcloud logging tail \"resource.type=cloud_run_job AND resource.labels.job_name=${JOB_NAME} AND resource.labels.location=${REGION}\" --project=${PROJECT_ID}"
echo ""
echo "8️⃣  GCP Console:"
echo "   https://console.cloud.google.com/logs/query?project=${PROJECT_ID}"
echo ""
echo "   Filter for API:"
echo "   resource.type=\"cloud_run_revision\""
echo "   resource.labels.service_name=\"${SERVICE_NAME}\""
echo "   resource.labels.location=\"${REGION}\""
echo ""
echo "   Filter for Worker:"
echo "   resource.type=\"cloud_run_job\""
echo "   resource.labels.job_name=\"${JOB_NAME}\""
echo "   resource.labels.location=\"${REGION}\""
echo ""

